Exercise10.class : Exercise10.java Buttons.class Canvas.class Data.class DesignElement.class ElementPanel.class FileIO.class FillPanel.class Palette.class SelectedPanel.class StrokePanel.class Design6.class Image.class
	javac Exercise10.java

Canvas.class : Canvas.java
	javac Canvas.java

Data.class : Data.java
	javac Data.java

DesignElement.class : DesignElement.java
	javac DesignElement.java

FileIO.class : FileIO.java
	javac FileIO.java

Buttons.class : Buttons.java
	javac Buttons.java

ElementPanel.class : ElementPanel.java
	javac ElementPanel.java

FillPanel.class : FillPanel.java
	javac FillPanel.java

Palette.class : Palette.java
	javac Palette.java

SelectedPanel.class : SelectedPanel.java
	javac SelectedPanel.java

StrokePanel.class : StrokePanel.java
	javac StrokePanel.java

Kaleidoscope.class : Kaleidoscope.java
	javac Kaleidoscope.java

Design8.class : Design8.java
	javac Design8.java

Design6.class : Design6.java
	javac Design6.java

Image.class : Image.java
	javac Image.java

clean :
	rm *.class

submit : Buttons.java Canvas.java Data.java DesignElement.java ElementPanel.java Exercise10.java FileIO.java FillPanel.java Palette.java SelectedPanel.java StrokePanel.java Design6.java Image.java makefile submissionid.txt submissionid.jpg submissionid6.jpg submissionidE10.pdf
	rm -rf submissionidE10
	mkdir submissionidE10
	cp Buttons.java submissionidE10
	cp Canvas.java submissionidE10
	cp Data.java submissionidE10
	cp Design6.java submissionidE10
	cp DesignElement.java submissionidE10
	cp ElementPanel.java submissionidE10
	cp Exercise10.java submissionidE10
	cp FileIO.java submissionidE10
	cp FillPanel.java submissionidE10
	cp Image.java submissionidE10
	cp Palette.java submissionidE10
	cp SelectedPanel.java submissionidE10
	cp StrokePanel.java submissionidE10
	cp makefile submissionidE10
	cp submissionid.txt submissionidE10
	cp submissionid.jpg submissionidE10
	cp submissionid6.jpg submissionidE10
	cp submissionidE10.pdf submissionidE10
	tar cfvz submissionidE10.tgz submissionidE10
	cp submissionidE10.tgz ~tiawatts/cs375drop

